### ISSUE TITLE
Right Thumbstick is inverted on the Controller Mapping prefabs

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Tilia.Input.UnityInputManager#37]
Due to an old issue where Unity Input Manager inverts Axis5, this was incorrectly implemented by not inverting the axis in the Input Manager and isntead setting the axis multipler on the VerticalAxis[5] to -1

The multiplier should be 1 as the axis is now correctly inverted when created.

**Comment by thestonefox** [comment]
Got a fix for this, waiting on zinnia PR

**Comment by extendreality** [comment]
fixed with https://github.com/ExtendRealityLtd/Tilia.Input.UnityInputManager/pull/40
