### ISSUE TITLE
Ensure axis sensitivity is set correctly and don't use built in Horizontal/Vertical as it's a messy config

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/Tilia.Input.UnityInputManager#38]
The axis sensitivity should be: 1
with a deadzone of: 0.001
and a gravity of: 0

Don't use Horizontal/Vertical, create two Tilia Horz and Vert that has full control over what the settings are without unity overriding it.

**Comment by thestonefox** [comment]
Got a fix for this, waiting on zinnia PR

**Comment by extendreality** [comment]
fixed with https://github.com/ExtendRealityLtd/Tilia.Input.UnityInputManager/pull/40
