### ISSUE TITLE
Oculus Touch Controller Menu Button assignment is wrong for Oculus QUEST

### ISSUE THREAD

**Issue by skelder** [ExtendRealityLtd/Tilia.Input.UnityInputManager#42]
* Code source: github
* Code version: 1.3.4
* Platform version: unity 2019.4
* 3rd party dependencies: none

### Steps to reproduce

Use the prefab Input.UnityInputManager.Oculus.TouchLeftController in the ControllerMappings Folder

### Expected behavior

React to menu button press

### Current behavior

No reaction

Currently the Settings for the ButtonStart_Press points to Joystick button 7, whereas for Oculus QUEST We have to change it to joystickbutton6.
I do not have Oculus desktop headset to test this with, so this may as well be isolated case for Quest headset only

**Comment by thestonefox** [comment]
It is listed as button 7 on the Unity docs

https://docs.unity3d.com/2018.3/Documentation/Manual/OculusControllers.html

So if it's wrong, then Unity are reporting it incorrectly
