### ISSUE TITLE
Filenames are too long

### ISSUE THREAD

**Issue by fschmidmichels** [ExtendRealityLtd/Tilia.Input.UnityInputManager#48]
### Environment

* Code source: github
* Code version: 1.12.2 (but does not matter much)
* Platform version: Unity 2019.4.11
* 3rd party dependencies: Not relevant

### Steps to reproduce

Created a project with this package and try to use the Github Desktop App on Windows
Or: Have a long direcotry name for your project and try to import this or other Tilia packages in Unity.

### Expected behavior

Github Desktop should work
or:
The package should import without problems in Unity

### Current behavior

error: lstat("HMI-VR-LAB/Library/PackageCache/io.extendreality.tilia.interactions.interactables.unity@1.12.2/Documentation/HowToGuides/PassingAFloatValueFromAnInteractorToAnInteractable/assets/images/DragAndDropActionPublisherIntoLeftControllerAlias.png"): Filename too long

--> Filenames are too long. And I only have A:\HMI-VR-LAB as my folder, so a very short  directory name.
This ist also a problem for the scripts, they do not get imported with some Visual Basic error message pertaining to a 255 (or 254?) character limit for files in VB if one uses a "long" directory path.

This is also a problem for many of the other packages.

Thank you for your work! I hope this can be resolved easily.

**Comment by thestonefox** [comment]
either enable windows 10 long filename support or move your project path to somewhere higher in your drive.

This is a common problem across many many repository packages in many different languages due to the 255 character limitation imposed in windows 10 by default. We cannot "fix" it. Even if we made folder names shorter then there would always be someone who still managed to exceed this filename limit so there's nothing we can do to please everyone

**Comment by fschmidmichels** [comment]
This is also a bug in Visual Studio 2019, there is no known fix! Peaople are going to encounter this problem eventually!

**Comment by thestonefox** [comment]
then your best bet is to move your project to a higher up directory on the drive

**Comment by fschmidmichels** [comment]
> then your best bet is to move your project to a higher up directory on the drive

As i wrote, I already have a very short directory path to the project.

**Comment by thestonefox** [comment]
This project is already being used by many people including me without any file name issues. There is no fix we can apply

**Comment by fschmidmichels** [comment]
You can shorten the filenames... As I said, this is also a problem with Visual Basic.

**Comment by thestonefox** [comment]
and as I said if we shorten the filenames then it breaks for someone else. This isn't a problem for many many other people so I suggest you look into increasing your windows 10 file length support. Also, this project has nothing to do with Visual Basic.

Git can be forced to support long file path names too.

**Comment by fschmidmichels** [comment]
Sorry, I mean Visual Studio of course. This has also nothing to to with the Windows file length support. An when you import the packages through unity, the scripts are parsed by Visual Studio, and then the import fails. But i solved the issue with git now, there is a config option for it.

**Comment by thestonefox** [comment]
This project works for many people including myself so if you're having an issue with filenames then that is nothing to do with a bug in this project. If you require further help I suggest leaving a message on the discord server and seeing if someone can aid you with your issue. https://www.vrtk.io/community.html
