### ISSUE TITLE
Using UnityInputManagerButtonAction sources, interactable's Hold Till Release doesn't work, behaves as Toggle

### ISSUE THREAD

**Issue by louspawn** [ExtendRealityLtd/Tilia.Input.UnityInputManager#56]
### Environment

* Code source: Tilia.Input.UnityInputManager
* Code version: 1.3.15
* Platform version: Unity 2020.2.1f1
* 3rd party dependencies: None

### Steps to reproduce

1. Create a new Unity project using the URP template.
2. Add dependencies for the Tracked Alias, the Spatial Simulator, the Interactables and the Unity Input Manager Tilia packages as described in the respective guides.
2.1 Ensure `https://registry.npmjs.org/` is part of `scopedRegistries` and `io.extendreality` is part of `scopes`.
2.2 Add `"io.extendreality.tilia.camerarigs.trackedalias.unity": "1.5.6"` to the `dependencies`.
2.3 Add `"io.extendreality.tilia.camerarigs.spatialsimulator.unity": "1.2.29"` to the `dependencies`.
2.4 Add `"io.extendreality.tilia.interactions.interactables.unity": "1.15.6"` to the `dependencies`.
2.5 Add `"io.extendreality.tilia.input.unityinputmanager": "1.3.15"` to the `dependencies`.
3. Create a new scene, delete the main camera and add a plane (as a  floor), a cube (as a table) and the following Prefabs: CameraRigs.TrackedAlias, CameraRigs.SpatialSimulator, Interactions.Interactable, Interactions.Interactor x 2, Input.UnityInputManager.ButtonAction x 2.
4. Rename one ButtonAction to GrabLeft, set the sources to size 1 and add the ButtonOne Input from the SpatialSimulator's LeftControllerInput to the list.
5. Rename the other Button Action to GrabRight, remove the UnityInputManagerButtonAction component, add a BooleanAction component, set the sources to size 1 and add the ButtonTwo Input from the SpatialSimulator's RightControllerInput to the list.
6. Add the SpatialSimulator to the TrackedAliasFacade Elements list of Camera Rigs.
7. Add one Interactor to the LeftControllerAlias and the other to the RightControllerAlias of the TrackedAlias.
8. Set the VelocityTracker of each Interactor to the respective ControllerAlias (Left and Right).
9. Set the GrabAction of the Left Interactor to the ButtonAction added on step 4.
10. Set the GrabAction of the Right Interactor to the BooleanAction added on step 5.
11. Change the scale of the Interactable to (0.1, 0.1, 0.1) and place it on the table.
12. On the Interactable set the GrabType to Hold Till Release, the PrimaryAction to Interactable.GrabAction.Follow and the SecondaryAction to Interactable.GrabAction.Swap.
13. Play the scene.

### Expected behavior

When grabbing the Interactable object on the table using the SpatialSimulator's left or right controllers it should drop after releasing the left or right mouse button respectively. 

### Current behavior

When grabbing the Interactable object with the left Interactor which uses the UnityInputManagerButtonAction script, it behaves as if the GrabType is set to Toggle, it doesn't drop after the left mouse button is released but only if you press it again. When grabbing it with the right Interactor which uses the BooleanAction it behaves as expected.

**Comment by thestonefox** [comment]
I don't think this is a bug, you're basically listening to the same button action twice

ButtonOne on the left controller and ButtonOne on the right controller in the simulator both point to the same button which is `Mouse 0` or the left mouse button

So if you have the same action as the source twice then it's going to be called twice

**Comment by louspawn** [comment]
That is not the case, I placed the same button just for demonstration purposes and to be more easily reproducible. I have tested it with other inputs as well and the behavior is the same.

But even if what you said was true, it doesn't explain why it works differently on the BooleanAction than it does on the UnityInputManagerButtonAction with the exact same sources.

**Comment by thestonefox** [comment]
can you update the steps with using two distinct inputs so it removes that from being a potential reason

**Comment by louspawn** [comment]
FYI it is not necessary for the sources to be two, it happens with one as well, I just had them in the original post like this in order to be able to see it happen with either hand.

I made the changes, and actually I added one more BooleanAction for the right hand with the second distinct action to highlight also the difference in behavior between this and the UnityInputManagerButtonAction.

I hope it is more clear now.

**Comment by thestonefox** [comment]
If you're trying to use a Unity Input Button Action as a proxy and you have the Keycode set to `None` (or anything else really) then you're going to hit this issue. Because the Unity Input Button Action is running every frame and calling `Process` every frame based on the state of the key press (because the old unity input system works on polling)

So if you try and link another source to it, then that other source when activated is going to set the action to true, but your very next frame it will set the action value to the state of the key in your proxy unity input button action, which isn't what you want.

You don't want to use Unity Input Button Actions like this, they should be the end point fed into a Boolean Action if you want to have multiple actions.

I'll close this out as this isn't a bug and is expected
