### ISSUE TITLE
NRE occurs during unguarded access of serialized properties (Unity 2021.2.4f1)

### ISSUE THREAD

**Issue by tibbyhayes** [ExtendRealityLtd/Tilia.Input.UnityInputManager#74]
If I import this package in Unity 2021.2.4f1 the following error occurs due to unguarded access on the below mentioned line.

Error: `InvalidOperationException: The operation is not possible when moved past all properties (Next returned false)`
Line: https://github.com/ExtendRealityLtd/Tilia.Input.UnityInputManager/blob/7d63fc5f3ab512aa02a6e7c7d30c5e849705b6fd/Editor/UnityInputManagerAxisCreator.cs#L186

Presumably, the fix is to have an `if` guard on the line above it: ` axis.Next(true);` that continues the scan.

**Comment by tibbyhayes** [comment]
Note that this only occurs when the MockHMD isn't installed as a plugin.

**Comment by thestonefox** [comment]
PR with fix https://github.com/ExtendRealityLtd/Tilia.Input.UnityInputManager/pull/75
